version: "3.7"
# Declaração dos serviços.
services:
 # Configuração do container do Metabase.
  metabase-docker:
    # Build da imagem a ser buscada.
    build: .
    # Nome do container.
    container_name: metabase
    # Permite escolher reiniciar caso o serviço pare.
    restart: always
    # Especificação do expose das portas.
    ports:
      - 3002:3000
    # Indicação do diretório para volume.  
    volumes:
    # Use um diretório que já esteja criado.
      - ./metabase-data:/metabase-data
    # Criação das váriaveis de ambiente.
    environment:
      # Nome do tipo de Banco.
      MB_DB_TYPE: postgres   
      # Nome do Banco.
      MB_DB_DBNAME: metabase  
      # Porta de Conexão.
      MB_DB_PORT: 5432  
      #  Nome do Usuário a se conectar no Banco.
      MB_DB_USER: metabase  
      # Nome da senha do Usuário.
      MB_DB_PASS: metabase  
      # Nome do Host de conexão.
      MB_DB_HOST: 192.168.4.28
